# Generated by Django 5.2.17 on 2026-08-30 04:27

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_green_wallet_redemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcpiProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='authorization_reference',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='token_uid',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='ocpi_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_requests', to='relay.ocpiprovider'),
        ),
        migrations.CreateModel(
            name='OcpiSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('external_session_id', models.CharField(max_length=36)),
                ('location_id', models.CharField(blank=True, max_length=36)),
                ('evse_uid', models.CharField(blank=True, max_length=36)),
                ('connector_id', models.CharField(blank=True, max_length=36)),
                ('token_uid', models.CharField(blank=True, max_length=36)),
                ('authorization_reference', models.CharField(blank=True, max_length=36)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('RESERVED', 'Reserved'), ('COMPLETED', 'Completed'), ('INVALID', 'Invalid')], default='PENDING', max_length=16)),
                ('kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('start_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField()),
                ('raw_payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='relay.ocpiprovider')),
            ],
        ),
        migrations.CreateModel(
            name='OcpiCdr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2)),
                ('party_id', models.CharField(max_length=3)),
                ('cdr_id', models.CharField(max_length=39)),
                ('external_session_id', models.CharField(blank=True, max_length=36)),
                ('token_uid', models.CharField(blank=True, max_length=36)),
                ('authorization_reference', models.CharField(blank=True, max_length=36)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('total_energy_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('total_time_seconds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('total_cost_excl_vat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost_incl_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_credit', models.BooleanField(default=False)),
                ('credit_reference_id', models.CharField(blank=True, max_length=39)),
                ('raw_payload', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('match_status', models.CharField(choices=[('matched', 'Matched'), ('needs_review', 'Needs review'), ('settled', 'Settled')], default='needs_review', max_length=16)),
                ('review_reason', models.CharField(blank=True, max_length=200)),
                ('matched_redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocpi_cdrs', to='relay.redemptionrequest')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cdrs', to='relay.ocpiprovider')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdrs', to='relay.ocpisession')),
            ],
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[('HOLD', 'Hold'), ('DEBIT', 'Debit'), ('RELEASE', 'Release'), ('REVERSAL', 'Reversal'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('units', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_label', models.CharField(default='kWh-equivalent', max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('cdr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='relay.ocpicdr')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='relay.ocpiprovider')),
                ('redemption_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='relay.redemptionrequest')),
            ],
        ),
        migrations.AddConstraint(
            model_name='ocpisession',
            constraint=models.UniqueConstraint(fields=('provider', 'country_code', 'party_id', 'external_session_id'), name='unique_ocpi_session_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='ocpicdr',
            constraint=models.UniqueConstraint(fields=('provider', 'cdr_id'), name='unique_cdr_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='walletledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_type', 'DEBIT')), fields=('cdr', 'entry_type'), name='unique_debit_per_cdr'),
        ),
    ]
