# Generated by Django 5.2.17 on 2026-09-02 03:37
#
# Adds Institution + Membership and a nullable `institution` FK to every
# tenant-scoped model. This is purely additive: existing rows get
# institution=NULL and remain fully functional (public reference data and
# create-only PII endpoints don't require an institution at all). Backfill
# plan: once real institutions are onboarded, assign `institution` on
# existing Profile/RouteSignal/EVParticipantSignal/GreenRouteCredit/
# RedemptionRequest rows via a data migration or admin tooling keyed off
# Profile.email domain or an explicit operator mapping -- until then, rows
# with institution=NULL are only visible to platform_admin users (see
# relay/permissions.py IsTenantMember / TenantScopedQuerySetMixin in
# relay/views.py).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0002_green_wallet_redemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=32)),
                ('contact_name', models.CharField(blank=True, max_length=160)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='charginghub',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_hubs', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='corridor',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridors', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='evparticipantsignal',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ev_participant_signals', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='greenroutecredit',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='green_route_credits', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemption_requests', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='relayzone',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relay_zones', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='routesignal',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_signals', to='relay.institution'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('platform_admin', 'Platform admin'), ('institution_admin', 'Institution admin'), ('program_staff', 'Program staff'), ('viewer', 'Viewer')], default='viewer', max_length=32)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='relay.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'institution'), name='unique_user_institution_membership')],
            },
        ),
    ]
