# Canonical institutional vertical slice.
# Django ORM is the canonical application-domain persistence layer for these
# models. This migration is intentionally separate from Supabase migration
# history; do not push new Supabase domain DDL until the remote/local history
# discrepancy is reconciled.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('relay', '0003_institution_charginghub_institution_and_more')]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='relay.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('general_location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='America/Los_Angeles', max_length=64)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='relay.program')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('source_type', models.CharField(default='csv', max_length=40)),
                ('provenance_note', models.TextField(blank=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], default='received', max_length=32)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_row_count', models.PositiveIntegerField(default=0)),
                ('invalid_row_count', models.PositiveIntegerField(default=0)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='relay.cohort')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='relay.datasource')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_payload', models.JSONField(default=dict)),
                ('normalized_payload', models.JSONField(default=dict)),
                ('is_valid', models.BooleanField(default=False)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_records', to='relay.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.CharField(blank=True, max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='error', max_length=16)),
                ('source_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='relay.sourcerecord')),
            ],
        ),
        migrations.CreateModel(
            name='CommuterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_ref', models.CharField(blank=True, max_length=120)),
                ('origin_zone', models.CharField(max_length=120)),
                ('destination_zone', models.CharField(max_length=120)),
                ('commute_mode', models.CharField(max_length=40)),
                ('days_per_week', models.PositiveSmallIntegerField(default=5)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, max_length=40)),
                ('ev_hybrid', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_records', to='relay.cohort')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_records', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_records', to='relay.site')),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commuter_record', to='relay.sourcerecord')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method_version', models.CharField(default='core-v1-prototype', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='relay.cohort')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='relay.importbatch')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='CorridorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_zone', models.CharField(max_length=120)),
                ('destination_zone', models.CharField(max_length=120)),
                ('commuter_count', models.PositiveIntegerField(default=0)),
                ('sov_count', models.PositiveIntegerField(default=0)),
                ('ev_hybrid_count', models.PositiveIntegerField(default=0)),
                ('compatibility_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score_explanation', models.JSONField(default=dict)),
                ('analysis_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridor_scores', to='relay.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='Rule2202CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('execution_mode', models.CharField(choices=[('database_functions', 'Verified database functions'), ('reference_simulation', 'Reference simulation')], max_length=32)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('calculation_version', models.CharField(default='rule2202-sql-202609020001', max_length=120)),
                ('deployment_verified', models.BooleanField(default=False)),
                ('source_note', models.TextField(blank=True)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule2202_run', to='relay.analysisrun')),
            ],
        ),
        migrations.CreateModel(
            name='Rule2202Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.CharField(max_length=80)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('explanation', models.TextField(blank=True)),
                ('calculation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='relay.rule2202calculationrun')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('summary', models.TextField()),
                ('findings', models.JSONField(default=dict)),
                ('recommended_action', models.TextField()),
                ('caveats', models.JSONField(default=list)),
                ('analysis_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision_card', to='relay.analysisrun')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cards', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cards', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], max_length=8)),
                ('filename', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sha256', models.CharField(max_length=64)),
                ('decision_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='relay.decisioncard')),
            ],
        ),
        migrations.AddConstraint(model_name='program', constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='unique_program_slug_per_institution')),
        migrations.AddConstraint(model_name='site', constraint=models.UniqueConstraint(fields=('program', 'slug'), name='unique_site_slug_per_program')),
        migrations.AddConstraint(model_name='cohort', constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_cohort_slug_per_site')),
        migrations.AddConstraint(model_name='sourcerecord', constraint=models.UniqueConstraint(fields=('import_batch', 'row_number'), name='unique_source_row_per_batch')),
        migrations.AddConstraint(model_name='rule2202result', constraint=models.UniqueConstraint(fields=('calculation_run', 'metric'), name='unique_rule2202_metric_per_run')),
    ]
