# Generated for Relay Rider institutional vertical slice.
# Canonical application persistence remains in the Django ORM. Production is
# expected to use PostgreSQL; Rule 2202 SQL functions are invoked as database
# calculation primitives rather than duplicating domain tables in Supabase.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('relay', '0004_green_wallet_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('site_type', models.CharField(default='worksite', max_length=64)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='relay.institution')),
            ],
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=160)),
                ('cohort_type', models.CharField(default='participant_group', max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('source_type', models.CharField(choices=[('csv', 'CSV import'), ('survey', 'Survey'), ('api', 'API'), ('manual', 'Manual entry'), ('synthetic', 'Synthetic fixture')], max_length=32)),
                ('provenance_label', models.CharField(choices=[('imported', 'Imported'), ('reported', 'Reported'), ('synthetic', 'Synthetic'), ('modeled', 'Modeled')], max_length=32)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='relay.institution')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='CommuteImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commute_imports', to='relay.cohort')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commute_imports', to='relay.datasource')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commute_imports', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commute_imports', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commute_imports', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='CommuterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=120)),
                ('origin_zone', models.CharField(max_length=120)),
                ('destination_zone', models.CharField(max_length=120)),
                ('commute_days', models.JSONField(default=list)),
                ('arrival_window', models.CharField(max_length=80)),
                ('departure_window', models.CharField(max_length=80)),
                ('schedule_flex_minutes', models.PositiveIntegerField(default=0)),
                ('current_mode', models.CharField(max_length=64)),
                ('occupants', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_fuel_type', models.CharField(blank=True, max_length=64)),
                ('parking_difficulty', models.CharField(blank=True, max_length=32)),
                ('ev_interest', models.BooleanField(default=False)),
                ('access_point_willing', models.BooleanField(default=False)),
                ('consent_confirmed', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid')], default='valid', max_length=16)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_payload', models.JSONField(blank=True, default=dict)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_records', to='relay.cohort')),
                ('commute_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='relay.commuteimport')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_records', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commuter_records', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='EngineScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score_type', models.CharField(default='intervention_opportunity', max_length=80)),
                ('score', models.PositiveSmallIntegerField()),
                ('factors', models.JSONField(default=dict)),
                ('explanation', models.TextField()),
                ('engine_version', models.CharField(max_length=64)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_scores', to='relay.cohort')),
                ('commuter_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engine_score', to='relay.commuterrecord')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_scores', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_scores', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='Rule2202CalculationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('calculation_version', models.CharField(default='rule2202-sql-202609020001', max_length=80)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('validation_snapshot', models.JSONField(default=dict)),
                ('blocked_reason', models.TextField(blank=True)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule2202_runs', to='relay.cohort')),
                ('commute_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule2202_runs', to='relay.commuteimport')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule2202_runs', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule2202_runs', to='relay.institution')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule2202_runs', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('reviewed', 'Reviewed')], default='draft', max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('finding', models.TextField()),
                ('evidence', models.JSONField(default=list)),
                ('interpretation', models.TextField(blank=True)),
                ('recommended_action', models.TextField()),
                ('owner_label', models.CharField(blank=True, max_length=160)),
                ('provenance', models.JSONField(default=dict)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cards', to='relay.cohort')),
                ('commute_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_cards', to='relay.commuteimport')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cards', to='relay.institution')),
                ('rule2202_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_cards', to='relay.rule2202calculationrun')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_cards', to='relay.site')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_audit_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_audit_events', to='relay.institution')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_audit_events', to='relay.site')),
            ],
            options={'ordering': ['occurred_at', 'id']},
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('institution', 'slug'), name='unique_site_slug_per_institution'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('site', 'slug'), name='unique_cohort_slug_per_site'),
        ),
        migrations.AddConstraint(
            model_name='commuterrecord',
            constraint=models.UniqueConstraint(fields=('commute_import', 'external_id'), name='unique_external_id_per_import'),
        ),
    ]
