# Generated by Django 5.2.17 on 2026-09-04 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relay', '0004_green_wallet_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBenefitPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('unit_label', models.CharField(default='Green Route Credits', max_length=80)),
                ('max_units_per_participant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_units_program_wide', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expiry_days', models.PositiveIntegerField(blank=True, help_text='Days after issuance a credit expires. NEEDS_FOUNDER_INPUT until a program default is approved.', null=True)),
                ('eligibility_description', models.TextField(blank=True, help_text='Descriptive-only eligibility notes. NEEDS_FOUNDER_INPUT for a binding eligibility rule.')),
                ('earning_rule_description', models.TextField(blank=True, help_text='Descriptive-only earning-rule notes. NEEDS_FOUNDER_INPUT for a binding earning rule.')),
                ('effective_start', models.DateField(blank=True, null=True)),
                ('effective_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=32)),
                ('evidence_label', models.CharField(choices=[('synthetic', 'Synthetic'), ('modeled', 'Modeled'), ('verified', 'Verified')], default='synthetic', max_length=32)),
                ('founder_approval_reference', models.CharField(blank=True, help_text='Reference to the founder/program approval record for this policy version. NEEDS_FOUNDER_INPUT until approved.', max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('ISSUE', 'Issue'), ('HOLD', 'Hold'), ('RELEASE', 'Release'), ('DEBIT', 'Debit'), ('REVERSAL', 'Reversal'), ('EXPIRE', 'Expire'), ('ADJUSTMENT', 'Adjustment')], max_length=16)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=160)),
                ('actor_reference', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='fulfillment_method',
            field=models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('manual_program_action', 'Manual program action')], default='unspecified', help_text="Records how a research-beta fulfillment decision was carried out. 'fulfilled' status is a program fulfillment decision recorded by an administrator; it is not evidence of an actual charge session and does not imply automatic settlement with a charging network.", max_length=32),
        ),
        migrations.AddField(
            model_name='redemptionrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddConstraint(
            model_name='redemptionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('credit', 'idempotency_key'), name='unique_credit_idempotency_key'),
        ),
        migrations.AddField(
            model_name='programbenefitpolicy',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_policies', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='relay.greenroutecredit'),
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_ledger_entries', to='relay.institution'),
        ),
        migrations.AddField(
            model_name='walletledgerentry',
            name='redemption_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='relay.redemptionrequest'),
        ),
        migrations.AddConstraint(
            model_name='programbenefitpolicy',
            constraint=models.UniqueConstraint(fields=('institution', 'version'), name='unique_institution_policy_version'),
        ),
    ]
