# Generated by Django 6.1 on 2026-08-17 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('route_signals', models.PositiveIntegerField(default=0)),
                ('ev_participants', models.PositiveIntegerField(default=0)),
                ('relay_zones', models.PositiveIntegerField(default=0)),
                ('parking_pressure', models.CharField(choices=[('low', 'Low'), ('medium-high', 'Medium-high'), ('high', 'High')], max_length=16)),
                ('pilot_readiness', models.CharField(choices=[('research', 'Research'), ('partner-review', 'Partner review'), ('needs-legal', 'Needs legal'), ('future', 'Future')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelayZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('corridor', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('review_status', models.CharField(choices=[('candidate', 'Candidate'), ('needs-partner', 'Needs partner'), ('needs-safety', 'Needs safety'), ('needs-property', 'Needs property'), ('needs-legal', 'Needs legal'), ('not-approved', 'Not approved')], default='candidate', max_length=32)),
                ('suggested_by_count', models.PositiveIntegerField(default=0)),
                ('partner_review_needed', models.BooleanField(default=False)),
                ('safety_review_needed', models.BooleanField(default=False)),
                ('property_review_needed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('commuter', 'Commuter'), ('route_participant', 'Route participant'), ('reviewer', 'Reviewer'), ('admin', 'Admin')], default='commuter', max_length=32)),
                ('adult_confirmed', models.BooleanField(default=False)),
                ('research_consent_given', models.BooleanField(default=False)),
                ('preferred_corridor', models.CharField(blank=True, max_length=255)),
                ('preferred_relay_zone_type', models.CharField(blank=True, max_length=255)),
                ('ev_hybrid_preference', models.CharField(blank=True, max_length=255)),
                ('privacy_preference', models.CharField(blank=True, max_length=255)),
                ('notification_preference', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corridor', models.CharField(max_length=255)),
                ('starting_area', models.CharField(max_length=255)),
                ('destination_area', models.CharField(max_length=255)),
                ('campus_affiliation', models.CharField(max_length=255)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('time_window', models.CharField(max_length=255)),
                ('route_type', models.CharField(choices=[('recurring', 'Recurring'), ('occasional', 'Occasional'), ('event', 'Event'), ('medical', 'Medical'), ('campus', 'Campus'), ('other', 'Other')], max_length=32)),
                ('relay_zone_type', models.JSONField(blank=True, default=list)),
                ('transit_options', models.JSONField(blank=True, default=list)),
                ('student_transit_pass', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not-sure', 'Not sure')], max_length=16)),
                ('incentive_interests', models.JSONField(blank=True, default=list)),
                ('ev_preference', models.CharField(choices=[('ev-only', 'EV only'), ('hybrid-ev', 'Hybrid or EV'), ('any', 'Any')], max_length=16)),
                ('max_walking_distance', models.CharField(max_length=255)),
                ('privacy_preference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending_verification', 'Pending verification'), ('pilot_review', 'Pilot review'), ('approved_for_demo', 'Approved for demo'), ('not_activated', 'Not activated'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('route_fit', models.CharField(blank=True, choices=[('high', 'High'), ('moderate', 'Moderate'), ('low', 'Low')], max_length=16)),
                ('green_route_credit', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overlap_potential', models.CharField(blank=True, max_length=16)),
                ('time_compatibility', models.CharField(blank=True, max_length=16)),
                ('relay_zone_fit', models.CharField(blank=True, max_length=16)),
                ('ev_hybrid_supply', models.CharField(blank=True, max_length=16)),
                ('parking_pressure', models.CharField(blank=True, max_length=16)),
                ('pilot_readiness', models.CharField(blank=True, max_length=32)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_signals', to='relay_core.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GreenRouteCredit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='pending', max_length=16)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_route_credits', to='relay_core.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EVParticipantSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('ev', 'EV'), ('phev', 'PHEV'), ('hybrid', 'Hybrid'), ('other', 'Other')], max_length=16)),
                ('vehicle_make', models.CharField(max_length=255)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_year', models.CharField(max_length=4)),
                ('starting_area', models.CharField(max_length=255)),
                ('destination_area', models.CharField(max_length=255)),
                ('travel_days', models.JSONField(blank=True, default=list)),
                ('time_window', models.CharField(max_length=255)),
                ('max_detour', models.CharField(max_length=255)),
                ('relay_zone_types', models.JSONField(blank=True, default=list)),
                ('feedback_call_willing', models.BooleanField(default=False)),
                ('reviews_accepted', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in-review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_participant_signals', to='relay_core.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
