-- Recovered migration-history anchor for 20260817024507 harden_deployment_fingerprint_20260817030000.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
