-- Recovered migration-history anchor for 20260808052202 saas_foundation_core.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
