-- Recovered migration-history anchor for 20260721051404 harden_rls_helper_functions.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
