-- Recovered migration-history anchor for 20260721051424 tighten_sensitive_column_constraints.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
