-- Recovered migration-history anchor for 20260808053031 saas_foundation_performance_hardening.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
