-- Recovered migration-history anchor for 20260808022415 add_research_beta_intake_staging.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
