-- Recovered migration-history anchor for 20260721051411 restrict_default_table_privileges.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
