-- Recovered migration-history anchor for 20260808022730 restrict_research_beta_rpc_to_anon.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
