-- Recovered migration-history anchor for 20260721051647 fort_knox_policy_role_scoping.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
