-- Recovered migration-history anchor for 20260808053122 saas_foundation_org_onboarding_status.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
