-- Recovered migration-history anchor for 20260808062308 operational_engine_hardening.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
