-- Recovered migration-history anchor for 20260817023652 authenticated_runtime_table_grants_20260817024500.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
