-- Recovered migration-history anchor for 20260721051829 optimize_rls_and_foreign_key_indexes.
-- Authoritative historical SQL is preserved in production supabase_migrations.schema_migrations.
-- Already applied; this anchor prevents accidental replay as a new migration.
